name: budgetly
description: A budget app that enhances how you manage your finances.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # GetX dependency
  get: ^4.6.5
  # Hive Dependency
  hive: ^2.2.3
  hive_flutter: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  # hive builder
  hive_generator: ^2.0.0
  build_runner: ^2.4.4
  # dependency injection
  get_it: ^7.6.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/lady.jpg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_black.ttf
        - asset: assets/fonts/poppins_bold.ttf
        - asset: assets/fonts/poppins_extra_bold.ttf
        - asset: assets/fonts/poppins_extra_light.ttf
        - asset: assets/fonts/poppins_light.ttf
        - asset: assets/fonts/poppins_medium.ttf
        - asset: assets/fonts/poppins_regular.ttf
        - asset: assets/fonts/poppins_semi_bold.ttf
        - asset: assets/fonts/poppins_thin.ttf
